version: '3.9'

services:
  # find-a-friend-api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: nodejs
  #   container_name: find-a-friend-api
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - find-a-friend-db
  
  find-a-friend-db:
    image: "bitnami/postgresql:latest"
    container_name: find-a-friend-db
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: findafriend
      POSTGRESQL_PASSWORD: findafriend
      POSTGRESQL_DATABASE: pets
    volumes:
      - find-a-friend-db-api:/var/lib/postgresql/data
    
volumes:
  find-a-friend-db-api: