version: '3.9'

services:
  # solid-api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: nodejs
  #   container_name: solid-api
  #   ports:
  #     - "3333:3333"
  #   depends_on:
  #     - solid-db
  
  solid-db:
    image: "bitnami/postgresql:latest"
    container_name: solid-db
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: apisolid
    volumes:
      - solid-db-api:/var/lib/postgresql/data
    
volumes:
  solid-db-api: