name: Run Unit Tests

on: 
  push:
    paths:
      - '03-api-solid/**'
      
jobs:
  run-unit-tests-solid-api:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: cd 03-api-solid
      - run: pnpm install --frozen-lockfile

      - run: pnpm run test