name: Run Unit Tests Find a Friend API

on: 
  push:
    paths:
      - '03-find-a-friend-api/**'
      
jobs:
  run-unit-tests-solid-api:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: cd 03-find-a-friend-api && pnpm install --frozen-lockfile
      - run: cd 03-find-a-friend-api && pnpm run test