name: Run Unit Tests

on: 
  push:
    paths:
      - '03-api-solid/**'
      
jobs:
  run-unit-tests-solid-api:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: cd 03-api-solid
      - run: npm ci

      - run: npm run test