name: Run E2E Tests

on: 
  pull_request:
    paths:
      - '03-api-solid/**'
      
jobs:
  run-e2e-tests-solid-api:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=apisolid

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: cd 03-api-solid && pnpm install --frozen-lockfile
      - run: cd 03-api-solid && pnpm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"